pipelines:
  default:
    - step:
        name: Install Dependencies
        image: node:8.10
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - build/**
    - step:
        name: Deploy to AWS
        deployment: production
        image: atlassian/pipelines-awscli
        script:
        - aws deploy push --application-name zephyr-api --s3-location s3://bitbucket-artifacts/live-zephyr-api --ignore-hidden-files
        - aws deploy create-deployment --application-name zephyr-api --s3-location bucket=bitbucket-artifacts,key=live-zephyr-api,bundleType=zip --deployment-group-name production