pipelines:
  default:
    - step:
        name: Install Dependencies
        image: node:8.10
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - '**/*'
    - step:
        name: Deploy to AWS
        script:
          - pipe: atlassian/aws-code-deploy:0.2.0
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: "upload"
              APPLICATION_NAME: "zephyr-api"
              ZIP_FILE: "live-zephyr-api.zip"
              S3_BUCKET: "bitbucket-artifacts"
          - pipe: atlassian/aws-code-deploy:0.2.0
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              COMMAND: "deploy"
              APPLICATION_NAME: "zephyr-api"
              DEPLOYMENT_GROUP: "production"
              WAIT: "true"
              S3_BUCKET: "bitbucket-artifacts"