---
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: {{APP_NAME}}-mongo
spec:
  version: "4.1.7-v1"
  replicas: 2
  replicaSet:
    name: rs0
  podTemplate:
    spec:
      args:
        - --transitionToAuth
  storage:
    storageClassName: "default"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
---
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: {{APP_NAME}}-redis
spec:
  version: 4.0-v2
  mode: Cluster
  cluster:
    master: 3
    replicas: 1
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 5Gi
    storageClassName: "default"
    accessModes:
      - ReadWriteOnce
  terminationPolicy: Pause
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-server
  labels:
    app: {{APP_NAME}}-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}-server
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-server
        commitHash: "{{CIRCLE_SHA1}}"
        buildNumber: "{{CIRCLE_BUILD_NUM}}"
    spec:
      dnsConfig:
        options:
          - name: single-request
      imagePullSecrets:
        - name: registry.dak.dev
      containers:
        - name: server
          image: {{DOCKER_REGISTRY_URL}}/{{DOCKER_IMAGE_NAME}}:{{CIRCLE_SHA1}}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_ENV
              value: "production"
            - name: AWS_REGION
              value: "{{AWS_REGION}}"
            - name: APP_MONGO_HOST
              value: "mongodb://{{APP_NAME}}-mongo"
            - name: APP_MONGO_REPLICA_SET
              value: "rs0"
            - name: APP_REDIS_HOST
              value: "{{APP_NAME}}-redis"
            - name: APP_REDIS_PORT
              value: "6379"
            - name: APP_REDIS_ENABLED
              value: "true"
#            - name: APP_MONGO_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: "{{APP_NAME}}-mongo-auth"
#                  key: password
#            - name: APP_MONGO_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: "{{APP_NAME}}-mongo-auth"
#                  key: username
          envFrom:
            - configMapRef:
                name: "{{APP_NAME}}-{{CIRCLE_BRANCH}}-env"
            - secretRef:
                name: "{{APP_NAME}}-{{CIRCLE_BRANCH}}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
spec:
  ports:
    - port: 4000
      name: web
      targetPort: 4000
  selector:
    app: {{APP_NAME}}-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{APP_HOSTNAME}}
  rules:
    - host: {{APP_HOSTNAME}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{APP_NAME}}-service
              servicePort: 4000

